name: test
on:
  push:
    branches:
    - "**"
  pull_request: {}
jobs:
  test:
    name: Run Test with Perl ${{ matrix.perl }} on ${{ matrix.mysql }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl:
          - '5.36'
          - '5.38'
        mysql:
          - 'mysql-5.6'
          - 'mysql-5.7'
          - 'mysql-8.0'
          - 'mariadb'
    steps:
      - uses: actions/checkout@v2
      - name: Setup perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: |
          author/ci_install_mysql.sh
          cpanm --quiet --installdeps --notest .
          if [[ "DATABASE_ADAPTER" == "mariadb" ]]; then
            cpanm DBD::MariaDB
          else
            cpanm DBD::mysql
          fi
          prove -lvr
        env:
          DATABASE_ADAPTER: ${{ matrix.mysql }}
